// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddJobHistory(arg1:main.JobHistory):Promise<void>;

export function AddPBSServer(arg1:main.PBSServer):Promise<void>;

export function AnalyzeBackup(arg1:Array<string>,arg2:Array<string>):Promise<Record<string, any>>;

export function CancelBackup():Promise<void>;

export function CancelSearch():Promise<void>;

export function CleanupAbandonedJobs():Promise<void>;

export function CreateBackupSplitPlan(arg1:Array<string>,arg2:string,arg3:Array<string>):Promise<Array<Record<string, any>>>;

export function DeletePBSServer(arg1:string):Promise<void>;

export function DeleteScheduledJob(arg1:string):Promise<void>;

export function DeleteScheduledJobFromMap(arg1:string):Promise<void>;

export function DiagnoseConfig():Promise<Record<string, any>>;

export function GenerateEncryptionKeyFile(arg1:string):Promise<main.EncryptionKeyInfo>;

export function GetBrand():Promise<main.Brand>;

export function GetConfig():Promise<main.Config>;

export function GetConfigWithHostname():Promise<Record<string, any>>;

export function GetDefaultPBSID():Promise<string>;

export function GetHostname():Promise<string>;

export function GetJobHistory():Promise<Array<main.JobHistory>>;

export function GetLastBackupDirs():Promise<Array<string>>;

export function GetPBSServer(arg1:string):Promise<main.PBSServer>;

export function GetScheduledJobs():Promise<Array<main.ScheduledJob>>;

export function GetScheduledJobsForAPI():Promise<Array<Record<string, any>>>;

export function GetServerFingerprint(arg1:string):Promise<string>;

export function GetSnapshotMeta(arg1:string,arg2:string,arg3:number):Promise<main.BackupMeta>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function HandleStartupRun():Promise<void>;

export function InspectEncryptionKeyFile(arg1:string):Promise<main.EncryptionKeyInfo>;

export function ListPBSServers():Promise<Array<main.PBSServer>>;

export function ListPhysicalDisks():Promise<Array<main.PhysicalDiskInfo>>;

export function ListSnapshotContents(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<Array<main.SnapshotEntry>>;

export function ListSnapshots(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function MinimizeToTray():Promise<void>;

export function OpenEncryptionKeyDialog():Promise<string>;

export function OpenEncryptionKeySaveDialog():Promise<string>;

export function OpenRestoreDestDialog():Promise<string>;

export function PinPBSServerFingerprint(arg1:string,arg2:string):Promise<void>;

export function PinServerFingerprint(arg1:string,arg2:string):Promise<void>;

export function RecalculateNextRuns():Promise<void>;

export function ReloadConfig():Promise<void>;

export function RequestElevation():Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:boolean,arg8:boolean,arg9:boolean,arg10:boolean,arg11:boolean):Promise<void>;

export function RunScheduledJobNow(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveScheduledJob(arg1:main.ScheduledJob):Promise<void>;

export function SaveScheduledJobFromMap(arg1:Record<string, any>):Promise<void>;

export function SearchFiles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:boolean):Promise<main.SearchResult>;

export function SetDefaultPBSServer(arg1:string):Promise<void>;

export function SetProgressCallbacks(arg1:string,arg2:any,arg3:any):Promise<void>;

export function SetupSystemTray():Promise<void>;

export function ShowFromTray():Promise<void>;

export function StartBackup(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:boolean,arg7:string):Promise<void>;

export function StartMachineBackup(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean,arg5:string):Promise<void>;

export function StartScheduler():Promise<void>;

export function StopScheduler():Promise<void>;

export function TestConnection(arg1:main.Config):Promise<void>;

export function TestPBSConnection(arg1:string):Promise<void>;

export function UpdatePBSServer(arg1:main.PBSServer):Promise<void>;

export function UpdateScheduledJob(arg1:main.ScheduledJob):Promise<void>;

export function UpdateScheduledJobFromMap(arg1:Record<string, any>):Promise<void>;

export function UpdateTrayTooltip(arg1:string):Promise<void>;
