// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJobHistory(arg1) {
  return window['go']['main']['App']['AddJobHistory'](arg1);
}

export function AddPBSServer(arg1) {
  return window['go']['main']['App']['AddPBSServer'](arg1);
}

export function AnalyzeBackup(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeBackup'](arg1, arg2);
}

export function CanModifyJobs() {
  return window['go']['main']['App']['CanModifyJobs']();
}

export function CancelBackup(arg1) {
  return window['go']['main']['App']['CancelBackup'](arg1);
}

export function CancelSearch() {
  return window['go']['main']['App']['CancelSearch']();
}

export function CleanupAbandonedJobs() {
  return window['go']['main']['App']['CleanupAbandonedJobs']();
}

export function ClearBackupContext() {
  return window['go']['main']['App']['ClearBackupContext']();
}

export function CreateBackupSplitPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBackupSplitPlan'](arg1, arg2, arg3);
}

export function DeletePBSServer(arg1) {
  return window['go']['main']['App']['DeletePBSServer'](arg1);
}

export function DeleteScheduledJob(arg1) {
  return window['go']['main']['App']['DeleteScheduledJob'](arg1);
}

export function DeleteScheduledJobFromMap(arg1) {
  return window['go']['main']['App']['DeleteScheduledJobFromMap'](arg1);
}

export function DiagnoseConfig() {
  return window['go']['main']['App']['DiagnoseConfig']();
}

export function GenerateEncryptionKeyFile(arg1) {
  return window['go']['main']['App']['GenerateEncryptionKeyFile'](arg1);
}

export function GetBackupContext() {
  return window['go']['main']['App']['GetBackupContext']();
}

export function GetBrand() {
  return window['go']['main']['App']['GetBrand']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigWithHostname() {
  return window['go']['main']['App']['GetConfigWithHostname']();
}

export function GetDefaultPBSID() {
  return window['go']['main']['App']['GetDefaultPBSID']();
}

export function GetFullConfigForAPI() {
  return window['go']['main']['App']['GetFullConfigForAPI']();
}

export function GetHostname() {
  return window['go']['main']['App']['GetHostname']();
}

export function GetJobHistory() {
  return window['go']['main']['App']['GetJobHistory']();
}

export function GetJobHistoryForAPI() {
  return window['go']['main']['App']['GetJobHistoryForAPI']();
}

export function GetLastBackupDirs() {
  return window['go']['main']['App']['GetLastBackupDirs']();
}

export function GetPBSServer(arg1) {
  return window['go']['main']['App']['GetPBSServer'](arg1);
}

export function GetScheduledJobs() {
  return window['go']['main']['App']['GetScheduledJobs']();
}

export function GetScheduledJobsForAPI() {
  return window['go']['main']['App']['GetScheduledJobsForAPI']();
}

export function GetServerFingerprint(arg1) {
  return window['go']['main']['App']['GetServerFingerprint'](arg1);
}

export function GetSnapshotMeta(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSnapshotMeta'](arg1, arg2, arg3);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HandleStartupRun() {
  return window['go']['main']['App']['HandleStartupRun']();
}

export function InspectEncryptionKeyFile(arg1) {
  return window['go']['main']['App']['InspectEncryptionKeyFile'](arg1);
}

export function ListBackupJobs() {
  return window['go']['main']['App']['ListBackupJobs']();
}

export function ListPBSServers() {
  return window['go']['main']['App']['ListPBSServers']();
}

export function ListPhysicalDisks() {
  return window['go']['main']['App']['ListPhysicalDisks']();
}

export function ListSnapshotContents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSnapshotContents'](arg1, arg2, arg3, arg4);
}

export function ListSnapshots(arg1, arg2) {
  return window['go']['main']['App']['ListSnapshots'](arg1, arg2);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MintPBSTicketForAPI(arg1) {
  return window['go']['main']['App']['MintPBSTicketForAPI'](arg1);
}

export function OpenDirectoryPicker() {
  return window['go']['main']['App']['OpenDirectoryPicker']();
}

export function OpenEncryptionKeyDialog() {
  return window['go']['main']['App']['OpenEncryptionKeyDialog']();
}

export function OpenEncryptionKeySaveDialog() {
  return window['go']['main']['App']['OpenEncryptionKeySaveDialog']();
}

export function OpenRestoreDestDialog() {
  return window['go']['main']['App']['OpenRestoreDestDialog']();
}

export function PinPBSServerFingerprint(arg1, arg2) {
  return window['go']['main']['App']['PinPBSServerFingerprint'](arg1, arg2);
}

export function PinServerFingerprint(arg1, arg2) {
  return window['go']['main']['App']['PinServerFingerprint'](arg1, arg2);
}

export function RecalculateNextRuns() {
  return window['go']['main']['App']['RecalculateNextRuns']();
}

export function RegisterBackupCancel(arg1, arg2) {
  return window['go']['main']['App']['RegisterBackupCancel'](arg1, arg2);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function RequestJobModificationElevation() {
  return window['go']['main']['App']['RequestJobModificationElevation']();
}

export function RestoreSnapshot(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function RunScheduledJobForAPI(arg1) {
  return window['go']['main']['App']['RunScheduledJobForAPI'](arg1);
}

export function RunScheduledJobNow(arg1) {
  return window['go']['main']['App']['RunScheduledJobNow'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFullConfigFromAPI(arg1) {
  return window['go']['main']['App']['SaveFullConfigFromAPI'](arg1);
}

export function SaveScheduledJob(arg1) {
  return window['go']['main']['App']['SaveScheduledJob'](arg1);
}

export function SaveScheduledJobFromMap(arg1) {
  return window['go']['main']['App']['SaveScheduledJobFromMap'](arg1);
}

export function SearchFiles(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetBackupContext(arg1, arg2) {
  return window['go']['main']['App']['SetBackupContext'](arg1, arg2);
}

export function SetDefaultPBSServer(arg1) {
  return window['go']['main']['App']['SetDefaultPBSServer'](arg1);
}

export function SetProgressCallbacks(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProgressCallbacks'](arg1, arg2, arg3);
}

export function SetupSystemTray() {
  return window['go']['main']['App']['SetupSystemTray']();
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function StartBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['StartBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartMachineBackup(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartMachineBackup'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartScheduler() {
  return window['go']['main']['App']['StartScheduler']();
}

export function StopScheduler() {
  return window['go']['main']['App']['StopScheduler']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestPBSConnection(arg1) {
  return window['go']['main']['App']['TestPBSConnection'](arg1);
}

export function TestPBSServerForAPI(arg1, arg2) {
  return window['go']['main']['App']['TestPBSServerForAPI'](arg1, arg2);
}

export function UpdatePBSServer(arg1) {
  return window['go']['main']['App']['UpdatePBSServer'](arg1);
}

export function UpdateScheduledJob(arg1) {
  return window['go']['main']['App']['UpdateScheduledJob'](arg1);
}

export function UpdateScheduledJobFromMap(arg1) {
  return window['go']['main']['App']['UpdateScheduledJobFromMap'](arg1);
}

export function UpdateTrayTooltip(arg1) {
  return window['go']['main']['App']['UpdateTrayTooltip'](arg1);
}
